---
domaintag:              dpd
publicdomain:           "{{domaintag}}.demo.li9.com"
localdomain:            "{{domaintag}}.li9.local"
KeyName:                "idrsa-{{domaintag}}"
StackName:              "UserOpenShift-{{domaintag}}"
root_public_key:        openshift_public_{{domaintag}}.key
docker_disk:            /dev/xvdh
save_inventory_file_locally: false
