---

- include: step_0_send_startservice_email.yml
  when: email is defined

- include: step_1_cloudformation.yml
  tags: cf

- hosts: openshift
  gather_facts: false
  become: false
  tasks:
   - name: wait until all hosts are up and running
     wait_for: port=22 search_regex=OpenSSH delay={{item}} timeout=300
     delegate_to: localhost
     with_items:
      - 1
      - 1

- include: step_2_register_on_redhat.yml
  tags: redhat

- include: step_3_apply_openshiftcommon_role.yml
  tags: oscommon

- include: step_4_pre_configure_systems.yml
  tags: preconf

- include: step_5_openshift_install.yml
  tags: install

- include: step_6_send_servicedeployed_email.yml
  when: email is defined

