---
- include: step_1_cloudformation.yml


- hosts: all
  gather_facts: false
  become: false
  tasks:
   - name: wait until all hosts are up and running
     wait_for: port=22 search_regex=OpenSSH delay=1 timeout=300
     delegate_to: localhost


- include: step_2_register_on_redhat.yml


#- hosts: master
#  become: true
#  vars_files:
#    - ../config.yml
#  roles:
#   - dnsserver
#


- hosts: all
  become: true
  vars_files:
    - ../config.yml
  roles:
   - openshiftcommon


- include: step_3_pre_configure_systems.yml


- include: step_4_openshift_install.yml


