- hosts: master
  become: true
  vars_files:
    - ../config.yml
  tasks:
   - name: run openshift ansible installer
     shell: ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml 
     async: 1800
     poll: 120
     tags: openshiftinstall

#   - name: enable Allow All authentication
#     replace: dest=/etc/origin/master/master-config.yaml regexp='(.+)DenyAllPasswordIdentityProvider$' replace='\1AllowAllPasswordIdentityProvider' backup=yes
#     notify: restart openshift master

   - name: enable node scheduler for master
     command: oadm  manage-node  --schedulable  master01.{{localdomain}}
     notify: restart openshift master

  handlers:
   - name: restart openshift master
     service: name=atomic-openshift-master state=restarted 
