---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars_files:
    - ../config.yml
  tasks:
    - name: create key pair {{KeyName}}
      ec2_key:
        name: "{{KeyName}}"
        ec2_region: us-east-1
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
      register: ec2_key

    - name: save private key
      copy:
        content: "{{ ec2_key.key.private_key }}"
        dest: "~/{{KeyName}}.pem"
        mode: 0600
      when: ec2_key|changed

    - name: get private key information
      command: cat ~/{{KeyName}}.pem
      register: private_key


    - name: launch ansible cloudformation {{StackName}}
      cloudformation:
        stack_name: "{{StackName}}"
        state: "present"
        region: "us-east-1"
        disable_rollback: true
        template: "../cloudformation/openshift.json"
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        template_parameters:
          KeyName: "{{KeyName}}"
          domaintag: "{{domaintag}}"
        tags:
          Stack: "{{StackName}}"
      register: cfres

    - name: send an email that cloudformation is done
      mail:
        subject: "OpenShift is almost ready"
        to: "{{email}}"
        from: Li9 Demo <do-not-reply@demo.li9.com>
        body: |
          The first step of OpenShift configuration is completed - AWS Instances were deployed
          Please be aware that system is still configuring your OpenShift Enterprise and it will take some time.
          Once it's ready you will receive a new email
          The following information is important to connect to the service:
          *) Master node: master01.{{publicdomain}}
          *) Nodes: node01.{{publicdomain}} and node02.{{publicdomain}}
          *) All servers are running under Red Hat Enterprise Linux 7.x
          *) All hosts are accessible via ssh
          *) SSH username: ec2-user
          *) SSH access type: only using a private key
          *) SSH private key is shown below:
          {{ private_key.stdout }}
          Thank you
          //Li9 team
      when: email is defined

#    - name: create ansible inventory file
#      template: src=../templates/ansible.hosts.j2 dest=~/inventory force=yes

    - name: add all hosts to dynamic inventory
      add_host:
        name: "{{item.name}}.{{localdomain}}"
        groups: "{{item.groups}}"
        ansible_host: "{{item.ip}}"
        ansible_connection: smart
        ansible_user: ec2-user
        ansible_ssh_private_key_file: ~/{{KeyName}}.pem
      with_items:
        - { name: node01,   groups: 'openshift,node01,nodes', ip: "{{cfres.stack_outputs.Node01}}" }
        - { name: node02,   groups: 'openshift,node02,nodes', ip: "{{cfres.stack_outputs.Node02}}" }
        - { name: master01, groups: 'openshift,master',       ip: "{{cfres.stack_outputs.Master}}" }
      changed_when: false

