---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars_files:
   - ../config.yml
  tasks:
   - name: send email that service is ordered
     mail:
      subject: "OpenShift {{publicdomain}} has been ordered"
      to: "{{email}}"
      from: Li9 Demo <do-not-reply@demo.li9.com>
      body: |
       OpenShift Enterprise 3.x service has been ordered on domain {{publicdomain}}
       Li9 Demo system started its deployment
       It will take ~ 25 mins
       Enjoy your demo environment
       //Li9 Demo system
